name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSHPRIVATEKEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@157.180.122.108 "
            cd /sertac/my-personal-website &&
            git pull origin main &&
            # our deployment commands here, e.g.:
            sudo systemctl restart nginx
          "
